<?php
/**
 *
 */

namespace OpenTHC\Bunk\Metrc\Packages;

use OpenTHC\Bunk\Module\METRC;

$ret = array();
$package = array(
	"Id" => 2,
	"Label" => "ABCDEF012345670000010042",
	"PackageType" => "Product",
	"SourceHarvestNames" => null,
	"LocationId" => null,
	"LocationName" => null,
	"LocationTypeName" => null,
	"Quantity" => 1.0,
	"UnitOfMeasureName" => "Ounces",
	"UnitOfMeasureAbbreviation" => "oz",
	"PatientLicenseNumber" => null,
	"ProductId" => 1,
	"ProductName" => "Buds",
	"ProductCategoryName" => "Buds",
	"ItemFromFacilityLicenseNumber" => null,
	"ItemFromFacilityName" => null,
	"ItemStrainName" => null,
	"ItemUnitCbdPercent" => null,
	"ItemUnitCbdContent" => null,
	"ItemUnitCbdContentUnitOfMeasureName" => null,
	"ItemUnitThcPercent" => null,
	"ItemUnitThcContent" => null,
	"ItemUnitThcContentUnitOfMeasureName" => null,
	"ItemUnitVolume" => null,
	"ItemUnitVolumeUnitOfMeasureName" => null,
	"ItemUnitWeight" => null,
	"ItemUnitWeightUnitOfMeasureName" => null,
	"ItemServingSize" => null,
	"ItemSupplyDurationDays" => null,
	"ItemUnitQuantity" => null,
	"ItemUnitQuantityUnitOfMeasureName" => null,
	"Note" => null,
	"PackagedDate" => "2014-11-29",
	"InitialLabTestingState" => "NotSubmitted",
	"LabTestingState" => "NotSubmitted",
	"LabTestingStateDate" => "2014-11-29",
	"IsProductionBatch" => false,
	"ProductionBatchNumber" => null,
	"SourceProductionBatchNumbers" => null,
	"IsTradeSample" => false,
	"IsDonation" => false,
	"IsDonationPersistent" => false,
	"SourcePackageIsDonation" => false,
	"IsTestingSample" => false,
	"IsProcessValidationTestingSample" => false,
	"ProductRequiresRemediation" => false,
	"ContainsRemediatedProduct" => false,
	"RemediationDate" => null,
	"ReceivedDateTime" => null,
	"ReceivedFromManifestNumber" => null,
	"ReceivedFromFacilityLicenseNumber" => null,
	"ReceivedFromFacilityName" => null,
	"IsOnHold" => false,
	"ArchivedDate" => null,
	"FinishedDate" => null,
	"LastModified" => "2021-02-17T15 =>10 =>04.6582141+00 =>00",
	"Item" => [
		"Id" => 1,
		"Name" => "Buds",
		"ProductCategoryName" => "Buds",
		"ProductCategoryType" => 0,
		"QuantityType" => 0,
		"DefaultLabTestingState" => 0,
		"UnitOfMeasureName" => null,
		"ApprovalStatus" => 0,
		"ApprovalStatusDateTime" => "0001-01-01T00 =>00 =>00+00 =>00",
		"StrainId" => null,
		"StrainName" => null,
		"AdministrationMethod" => null,
		"UnitCbdPercent" => null,
		"UnitCbdContent" => null,
		"UnitCbdContentUnitOfMeasureName" => null,
		"UnitCbdContentDose" => null,
		"UnitCbdContentDoseUnitOfMeasureName" => null,
		"UnitThcPercent" => null,
		"UnitThcContent" => null,
		"UnitThcContentUnitOfMeasureName" => null,
		"UnitThcContentDose" => null,
		"UnitThcContentDoseUnitOfMeasureName" => null,
		"UnitVolume" => null,
		"UnitVolumeUnitOfMeasureName" => null,
		"UnitWeight" => null,
		"UnitWeightUnitOfMeasureName" => null,
		"ServingSize" => null,
		"SupplyDurationDays" => null,
		"NumberOfDoses" => null,
		"UnitQuantity" => null,
		"UnitQuantityUnitOfMeasureName" => null,
		"Ingredients" => null,
		"Description" => null,
		"IsUsed" => false
	],
);
$ret[] = $package;

/**
 * USA/OK Examples
 */
$package = array(
	"ArchivedDate" => "",
	"ContainsRemediatedProduct" => "",
	"FinishedDate" => "",
	"Id" => "20221291200",
	"InitialLabTestingState" => "NotRequired",
	"IsDonation" => "",
	"IsDonationPersistent" => "",
	"IsOnHold" => "",
	"IsProcessValidationTestingSample" => "",
	"IsProductionBatch" => "",
	"IsTestingSample" => "",
	"IsTradeSample" => "",
	"IsTradeSamplePersistent" => "",
	"Item" => array(
		"Id" => 20221291200,
		"Name" => " 4bfc877f Alpha Product - UPDATE",
		"IsUsed" => "",
		"StrainId" => 202,
		"StrainName" => "4bfc877f Alpha Variety - UPDATE",
		"UnitVolume" => "",
		"UnitWeight" => "",
		"Description" => "",
		"ServingSize" => "",
		"QuantityType" => "CountBased",
		"UnitQuantity" => "",
		"NumberOfDoses" => "",
		"ApprovalStatus" => "Approved",
		"UnitCbdContent" => "",
		"UnitCbdPercent" => "",
		"UnitThcContent" => "",
		"UnitThcPercent" => "",
		"PublicIngredients" => "",
		"UnitOfMeasureName" => "Each",
		"SupplyDurationDays" => "",
		"UnitCbdContentDose" => "",
		"UnitThcContentDose" => "",
		"ProductCategoryName" => "Mature Plants",
		"ProductCategoryType" => "Plants",
		"AdministrationMethod" => "",
		"ApprovalStatusDateTime" => "2021-03-24T07:30:17+00:00",
		"DefaultLabTestingState" => "NotRequired",
		"UnitVolumeUnitOfMeasureName" => "",
		"UnitWeightUnitOfMeasureName" => "",
		"UnitQuantityUnitOfMeasureName" => "",
		"UnitCbdContentUnitOfMeasureName" => "",
		"UnitThcContentUnitOfMeasureName" => "",
		"UnitCbdContentDoseUnitOfMeasureName" => "",
		"UnitThcContentDoseUnitOfMeasureName" => "",
	),
	"ItemFromFacilityLicenseNumber" => "4a-X0003",
	"ItemFromFacilityName" => "AK MISHMASH IMMERSION, LLC",
	"LabTestingState" => "NotRequired",
	"LabTestingStateDate" => "2021-03-15",
	"Label" => "ABCDEF012345670000014711",
	"LastModified" => "2022-05-09T15:52:10-05:00",
	"LocationId" => null,
	"LocationName" => null,
	"LocationTypeName" => null,
	"Note" => "",
	"PackageType" => "ImmaturePlant",
	"PackagedDate" => "2021-03-15",
	"PatientLicenseNumber" => "",
	"ProductRequiresRemediation" => "",
	"ProductionBatchNumber" => "",
	"Quantity" => "3000",
	"ReceivedDateTime" => "",
	"ReceivedFromFacilityLicenseNumber" => "",
	"ReceivedFromFacilityName" => "",
	"ReceivedFromManifestNumber" => "",
	"RemediationDate" => "",
	"SourceHarvestCount" => " 0",
	"SourceHarvestNames" => "",
	"SourcePackageCount" => " 0",
	"SourcePackageIsDonation" => "",
	"SourcePackageIsTradeSample" => "",
	"SourceProcessingJobCount" => " 0",
	"SourceProductionBatchNumbers" => "",
	"UnitOfMeasureAbbreviation" => " ea",
	"UnitOfMeasureName" => " Each",
);
$ret[] = $package;

return $RES->withJSON($ret);
