<?php
/**
 *
 */

namespace OpenTHC\Bunk\Metrc\Transfers;

use OpenTHC\Bunk\Module\METRC;

$ret = array(
	[
		"PackageId"=> 1,
		"PackageLabel"=> "ABCDEF012345670000010026",
		"PackageType"=> "Product",
		"SourceHarvestNames"=> null,
		"SourcePackageLabels"=> null,
		"ProductName"=> "Buds",
		"ProductCategoryName"=> "Buds",
		"ItemStrainName"=> null,
		"ItemUnitCbdPercent"=> null,
		"ItemUnitCbdContent"=> null,
		"ItemUnitCbdContentUnitOfMeasureName"=> null,
		"ItemUnitCbdContentDose"=> null,
		"ItemUnitCbdContentDoseUnitOfMeasureName"=> null,
		"ItemUnitThcPercent"=> null,
		"ItemUnitThcContent"=> null,
		"ItemUnitThcContentUnitOfMeasureName"=> null,
		"ItemUnitThcContentDose"=> null,
		"ItemUnitThcContentDoseUnitOfMeasureName"=> null,
		"ItemUnitVolume"=> null,
		"ItemUnitVolumeUnitOfMeasureName"=> null,
		"ItemUnitWeight"=> null,
		"ItemUnitWeightUnitOfMeasureName"=> null,
		"ItemServingSize"=> null,
		"ItemSupplyDurationDays"=> null,
		"ItemUnitQuantity"=> null,
		"ItemUnitQuantityUnitOfMeasureName"=> null,
		"LabTestingState"=> "NotSubmitted",
		"ProductionBatchNumber"=> null,
		"IsTradeSample"=> false,
		"IsDonation"=> false,
		"SourcePackageIsDonation"=> false,
		"IsTestingSample"=> false,
		"ProductRequiresRemediation"=> false,
		"ContainsRemediatedProduct"=> false,
		"RemediationDate"=> null,
		"ShipmentPackageState"=> "Accepted",
		"ShippedQuantity"=> 10.0,
		"ShippedUnitOfMeasureName"=> "Ounces",
		"GrossUnitOfWeightName"=> null,
		"ReceivedQuantity"=> 10.0,
		"ReceivedUnitOfMeasureName"=> "Ounces"
		],
		[
		"PackageId"=> 2,
		"PackageLabel"=> "ABCDEF012345670000010027",
		"PackageType"=> "Product",
		"SourceHarvestNames"=> null,
		"SourcePackageLabels"=> null,
		"ProductName"=> "Buds",
		"ProductCategoryName"=> "Buds",
		"ItemStrainName"=> null,
		"ItemUnitCbdPercent"=> null,
		"ItemUnitCbdContent"=> null,
		"ItemUnitCbdContentUnitOfMeasureName"=> null,
		"ItemUnitCbdContentDose"=> null,
		"ItemUnitCbdContentDoseUnitOfMeasureName"=> null,
		"ItemUnitThcPercent"=> null,
		"ItemUnitThcContent"=> null,
		"ItemUnitThcContentUnitOfMeasureName"=> null,
		"ItemUnitThcContentDose"=> null,
		"ItemUnitThcContentDoseUnitOfMeasureName"=> null,
		"ItemUnitVolume"=> null,
		"ItemUnitVolumeUnitOfMeasureName"=> null,
		"ItemUnitWeight"=> null,
		"ItemUnitWeightUnitOfMeasureName"=> null,
		"ItemServingSize"=> null,
		"ItemSupplyDurationDays"=> null,
		"ItemUnitQuantity"=> null,
		"ItemUnitQuantityUnitOfMeasureName"=> null,
		"LabTestingState"=> "NotSubmitted",
		"ProductionBatchNumber"=> null,
		"IsTradeSample"=> false,
		"IsDonation"=> false,
		"SourcePackageIsDonation"=> false,
		"IsTestingSample"=> false,
		"ProductRequiresRemediation"=> false,
		"ContainsRemediatedProduct"=> false,
		"RemediationDate"=> null,
		"ShipmentPackageState"=> "Rejected",
		"ShippedQuantity"=> 10.0,
		"ShippedUnitOfMeasureName"=> "Ounces",
		"GrossUnitOfWeightName"=> null,
		"ReceivedQuantity"=> null,
		"ReceivedUnitOfMeasureName"=> null
	]
);

return $RES->withJSON($ret);
