<?php
/**
 *
 */

namespace OpenTHC\Bunk\METRC\Item;

use OpenTHC\Bunk\Module\METRC;

$ret = array(
	[
		"Id" =>  1,
		"Name" =>  "Buds",
		"ProductCategoryName" =>  "Buds",
		"ProductCategoryType" =>  "Buds",
		"QuantityType" =>  "WeightBased",
		"DefaultLabTestingState" =>  "AwaitingConfirmation",
		"UnitOfMeasureName" =>  "Ounces",
		"ApprovalStatus" =>  "Approved",
		"ApprovalStatusDateTime" =>  "0001-01-01T00 => 00 => 00+00 => 00",
		"StrainId" =>  1,
		"StrainName" =>  "Spring Hill Kush",
		"AdministrationMethod" =>  null,
		"UnitCbdPercent" =>  null,
		"UnitCbdContent" =>  null,
		"UnitCbdContentUnitOfMeasureName" =>  null,
		"UnitCbdContentDose" =>  null,
		"UnitCbdContentDoseUnitOfMeasureName" =>  null,
		"UnitThcPercent" =>  null,
		"UnitThcContent" =>  null,
		"UnitThcContentUnitOfMeasureName" =>  null,
		"UnitThcContentDose" =>  null,
		"UnitThcContentDoseUnitOfMeasureName" =>  null,
		"UnitVolume" =>  null,
		"UnitVolumeUnitOfMeasureName" =>  null,
		"UnitWeight" =>  null,
		"UnitWeightUnitOfMeasureName" =>  null,
		"ServingSize" =>  null,
		"SupplyDurationDays" =>  null,
		"NumberOfDoses" =>  null,
		"UnitQuantity" =>  null,
		"UnitQuantityUnitOfMeasureName" =>  null,
		"Ingredients" =>  null,
		"Description" =>  null,
		"IsUsed" =>  false
	],
	[
		"Id" =>  3,
		"Name" =>  "Brownies",
		"ProductCategoryName" =>  "Infused Edibles",
		"ProductCategoryType" =>  "InfusedEdible",
		"QuantityType" =>  "CountBased",
		"DefaultLabTestingState" =>  "NotSubmitted",
		"UnitOfMeasureName" =>  "Each",
		"ApprovalStatus" =>  "Approved",
		"ApprovalStatusDateTime" =>  "0001-01-01T00 => 00 => 00+00 => 00",
		"StrainId" =>  null,
		"StrainName" =>  null,
		"AdministrationMethod" =>  null,
		"UnitCbdPercent" =>  null,
		"UnitCbdContent" =>  null,
		"UnitCbdContentUnitOfMeasureName" =>  null,
		"UnitCbdContentDose" =>  null,
		"UnitCbdContentDoseUnitOfMeasureName" =>  null,
		"UnitThcPercent" =>  null,
		"UnitThcContent" =>  2.0,
		"UnitThcContentUnitOfMeasureName" =>  "Milligrams",
		"UnitThcContentDose" =>  null,
		"UnitThcContentDoseUnitOfMeasureName" =>  null,
		"UnitVolume" =>  null,
		"UnitVolumeUnitOfMeasureName" =>  null,
		"UnitWeight" =>  15.0,
		"UnitWeightUnitOfMeasureName" =>  "Ounces",
		"ServingSize" =>  null,
		"SupplyDurationDays" =>  null,
		"NumberOfDoses" =>  null,
		"UnitQuantity" =>  null,
		"UnitQuantityUnitOfMeasureName" =>  null,
		"Ingredients" =>  null,
		"Description" =>  null,
		"IsUsed" =>  false
	],
	[
		"Id" =>  4,
		"Name" =>  "Bulk Buds Alpha",
		"ProductCategoryName" =>  "Buds",
		"ProductCategoryType" =>  "Buds",
		"QuantityType" =>  "WeightBased",
		"DefaultLabTestingState" =>  "NotSubmitted",
		"UnitOfMeasureName" =>  "Grams",
		"ApprovalStatus" =>  "Approved",
		"ApprovalStatusDateTime" =>  "0001-01-01T00 => 00 => 00+00 => 00",
		"StrainId" =>  202,
		"StrainName" =>  "Alpha Strain",
		"AdministrationMethod" =>  null,
		"UnitCbdPercent" =>  null,
		"UnitCbdContent" =>  null,
		"UnitCbdContentUnitOfMeasureName" =>  null,
		"UnitCbdContentDose" =>  null,
		"UnitCbdContentDoseUnitOfMeasureName" =>  null,
		"UnitThcPercent" =>  null,
		"UnitThcContent" =>  2.0,
		"UnitThcContentUnitOfMeasureName" =>  "Milligrams",
		"UnitThcContentDose" =>  null,
		"UnitThcContentDoseUnitOfMeasureName" =>  null,
		"UnitVolume" =>  null,
		"UnitVolumeUnitOfMeasureName" =>  null,
		"UnitWeight" =>  15.0,
		"UnitWeightUnitOfMeasureName" =>  "Grams",
		"ServingSize" =>  null,
		"SupplyDurationDays" =>  null,
		"NumberOfDoses" =>  null,
		"UnitQuantity" =>  null,
		"UnitQuantityUnitOfMeasureName" =>  null,
		"Ingredients" =>  null,
		"Description" =>  null,
		"IsUsed" =>  false
	],

	[
		'Id' => 20221291200,
		'Name' => '4bfc877f Alpha Product - UPDATE',
		'IsUsed' => true,
		'StrainId' => 202,
		'StrainName' => '4bfc877f Alpha Variety - UPDATE',
		'UnitVolume' => NULL,
		'UnitWeight' => NULL,
		'Description' => '',
		'ServingSize' => '',
		'QuantityType' => 'CountBased',
		'UnitQuantity' => NULL,
		'NumberOfDoses' => NULL,
		'ApprovalStatus' => 'Approved',
		'UnitCbdContent' => NULL,
		'UnitCbdPercent' => NULL,
		'UnitThcContent' => NULL,
		'UnitThcPercent' => NULL,
		'PublicIngredients' => '',
		'UnitOfMeasureName' => 'Each',
		'SupplyDurationDays' => NULL,
		'UnitCbdContentDose' => NULL,
		'UnitThcContentDose' => NULL,
		'ProductCategoryName' => 'Mature Plants',
		'ProductCategoryType' => 'Plants',
		'AdministrationMethod' => '',
		'ApprovalStatusDateTime' => '2021-03-24T07:30:17+00:00',
		'DefaultLabTestingState' => 'NotRequired',
		'UnitVolumeUnitOfMeasureName' => NULL,
		'UnitWeightUnitOfMeasureName' => NULL,
		'UnitQuantityUnitOfMeasureName' => NULL,
		'UnitCbdContentUnitOfMeasureName' => NULL,
		'UnitThcContentUnitOfMeasureName' => NULL,
		'UnitCbdContentDoseUnitOfMeasureName' => NULL,
		'UnitThcContentDoseUnitOfMeasureName' => NULL,
	]
);

return $RES->withJSON($ret);
