<?php

	namespace OpenTHC\Bunk\METRC\Item;
	use OpenTHC\Bunk\Module\METRC;

	$ret = array(
		[
			"Id" =>  1,
			"Name" =>  "Buds",
			"ProductCategoryName" =>  "Buds",
			"ProductCategoryType" =>  "Buds",
			"QuantityType" =>  "WeightBased",
			"DefaultLabTestingState" =>  "AwaitingConfirmation",
			"UnitOfMeasureName" =>  "Ounces",
			"ApprovalStatus" =>  "Approved",
			"ApprovalStatusDateTime" =>  "0001-01-01T00 => 00 => 00+00 => 00",
			"StrainId" =>  1,
			"StrainName" =>  "Spring Hill Kush",
			"AdministrationMethod" =>  null,
			"UnitCbdPercent" =>  null,
			"UnitCbdContent" =>  null,
			"UnitCbdContentUnitOfMeasureName" =>  null,
			"UnitCbdContentDose" =>  null,
			"UnitCbdContentDoseUnitOfMeasureName" =>  null,
			"UnitThcPercent" =>  null,
			"UnitThcContent" =>  null,
			"UnitThcContentUnitOfMeasureName" =>  null,
			"UnitThcContentDose" =>  null,
			"UnitThcContentDoseUnitOfMeasureName" =>  null,
			"UnitVolume" =>  null,
			"UnitVolumeUnitOfMeasureName" =>  null,
			"UnitWeight" =>  null,
			"UnitWeightUnitOfMeasureName" =>  null,
			"ServingSize" =>  null,
			"SupplyDurationDays" =>  null,
			"NumberOfDoses" =>  null,
			"UnitQuantity" =>  null,
			"UnitQuantityUnitOfMeasureName" =>  null,
			"Ingredients" =>  null,
			"Description" =>  null,
			"IsUsed" =>  false
		  ],
		  [
			"Id" =>  3,
			"Name" =>  "Brownies",
			"ProductCategoryName" =>  "Infused Edibles",
			"ProductCategoryType" =>  "InfusedEdible",
			"QuantityType" =>  "CountBased",
			"DefaultLabTestingState" =>  "NotSubmitted",
			"UnitOfMeasureName" =>  "Each",
			"ApprovalStatus" =>  "Approved",
			"ApprovalStatusDateTime" =>  "0001-01-01T00 => 00 => 00+00 => 00",
			"StrainId" =>  null,
			"StrainName" =>  null,
			"AdministrationMethod" =>  null,
			"UnitCbdPercent" =>  null,
			"UnitCbdContent" =>  null,
			"UnitCbdContentUnitOfMeasureName" =>  null,
			"UnitCbdContentDose" =>  null,
			"UnitCbdContentDoseUnitOfMeasureName" =>  null,
			"UnitThcPercent" =>  null,
			"UnitThcContent" =>  2.0,
			"UnitThcContentUnitOfMeasureName" =>  "Milligrams",
			"UnitThcContentDose" =>  null,
			"UnitThcContentDoseUnitOfMeasureName" =>  null,
			"UnitVolume" =>  null,
			"UnitVolumeUnitOfMeasureName" =>  null,
			"UnitWeight" =>  15.0,
			"UnitWeightUnitOfMeasureName" =>  "Ounces",
			"ServingSize" =>  null,
			"SupplyDurationDays" =>  null,
			"NumberOfDoses" =>  null,
			"UnitQuantity" =>  null,
			"UnitQuantityUnitOfMeasureName" =>  null,
			"Ingredients" =>  null,
			"Description" =>  null,
			"IsUsed" =>  false
		  ],
	);

	$RES->withJSON($ret);