<?php
/**
 * SPDX-License-Identifier: MIT
 */

namespace OpenTHC\Bunk\METRC\Item;

use OpenTHC\Bunk\Module\METRC;

$ret = array(
	[
		"Name" =>  "Buds",
		"ProductCategoryType" =>  "Buds",
		"QuantityType" =>  "WeightBased",
		"RequiresStrain" =>  true,
		"RequiresItemBrand" =>  false,
		"RequiresAdministrationMethod" =>  false,
		"RequiresUnitCbdPercent" =>  false,
		"RequiresUnitCbdContent" =>  false,
		"RequiresUnitCbdContentDose" =>  false,
		"RequiresUnitThcPercent" =>  false,
		"RequiresUnitThcContent" =>  false,
		"RequiresUnitThcContentDose" =>  false,
		"RequiresUnitVolume" =>  false,
		"RequiresUnitWeight" =>  false,
		"RequiresServingSize" =>  false,
		"RequiresSupplyDurationDays" =>  false,
		"RequiresNumberOfDoses" =>  false,
		"RequiresIngredients" =>  false,
		"RequiresDescription" =>  false,
		"RequiresProductPhotos" =>  0,
		"RequiresLabelPhotos" =>  0,
		"RequiresPackagingPhotos" =>  0,
		"CanContainSeeds" =>  true,
		"CanBeRemediated" =>  true
	],
	[
		"Name" =>  "Immature Plants",
		"ProductCategoryType" =>  "Plants",
		"QuantityType" =>  "CountBased",
		"RequiresStrain" =>  true,
		"RequiresItemBrand" =>  false,
		"RequiresAdministrationMethod" =>  false,
		"RequiresUnitCbdPercent" =>  false,
		"RequiresUnitCbdContent" =>  false,
		"RequiresUnitCbdContentDose" =>  false,
		"RequiresUnitThcPercent" =>  false,
		"RequiresUnitThcContent" =>  false,
		"RequiresUnitThcContentDose" =>  false,
		"RequiresUnitVolume" =>  false,
		"RequiresUnitWeight" =>  false,
		"RequiresServingSize" =>  false,
		"RequiresSupplyDurationDays" =>  false,
		"RequiresNumberOfDoses" =>  false,
		"RequiresIngredients" =>  false,
		"RequiresDescription" =>  false,
		"RequiresProductPhotos" =>  0,
		"RequiresLabelPhotos" =>  0,
		"RequiresPackagingPhotos" =>  0,
		"CanContainSeeds" =>  true,
		"CanBeRemediated" =>  false
	],
	[
		"Name" =>  "Infused",
		"ProductCategoryType" =>  "InfusedEdible",
		"QuantityType" =>  "CountBased",
		"RequiresStrain" =>  false,
		"RequiresItemBrand" =>  false,
		"RequiresAdministrationMethod" =>  false,
		"RequiresUnitCbdPercent" =>  false,
		"RequiresUnitCbdContent" =>  false,
		"RequiresUnitCbdContentDose" =>  false,
		"RequiresUnitThcPercent" =>  false,
		"RequiresUnitThcContent" =>  true,
		"RequiresUnitThcContentDose" =>  false,
		"RequiresUnitVolume" =>  false,
		"RequiresUnitWeight" =>  true,
		"RequiresServingSize" =>  false,
		"RequiresSupplyDurationDays" =>  false,
		"RequiresNumberOfDoses" =>  false,
		"RequiresIngredients" =>  false,
		"RequiresDescription" =>  false,
		"RequiresProductPhotos" =>  0,
		"RequiresLabelPhotos" =>  0,
		"RequiresPackagingPhotos" =>  0,
		"CanContainSeeds" =>  false,
		"CanBeRemediated" =>  true
	],
	[
		"Name" =>  "Infused Liquid",
		"ProductCategoryType" =>  "InfusedEdible",
		"QuantityType" =>  "CountBased",
		"RequiresStrain" =>  false,
		"RequiresItemBrand" =>  false,
		"RequiresAdministrationMethod" =>  false,
		"RequiresUnitCbdPercent" =>  false,
		"RequiresUnitCbdContent" =>  false,
		"RequiresUnitCbdContentDose" =>  false,
		"RequiresUnitThcPercent" =>  false,
		"RequiresUnitThcContent" =>  true,
		"RequiresUnitThcContentDose" =>  false,
		"RequiresUnitVolume" =>  true,
		"RequiresUnitWeight" =>  false,
		"RequiresServingSize" =>  false,
		"RequiresSupplyDurationDays" =>  false,
		"RequiresNumberOfDoses" =>  false,
		"RequiresIngredients" =>  false,
		"RequiresDescription" =>  false,
		"RequiresProductPhotos" =>  0,
		"RequiresLabelPhotos" =>  0,
		"RequiresPackagingPhotos" =>  0,
		"CanContainSeeds" =>  false,
		"CanBeRemediated" =>  true
	]
);

return $RES->withJSON($ret);
